Added mermaid format to cycle:render command
spiral/cycle-bridge pull request #61
Opened 2022-11-21 12:15 UTC by kastahov

2022-11-21 13:18 UTC, roxblnfk commented on src/Console/Command/CycleOrm/RenderCommand.php
> +                sprintf("Format `%s` doesn't exists.", $this->argument('format'))
```suggestion
                sprintf("Format `%s` isn't supported.", $this->argument('format'))
```

2022-12-16 07:19 UTC, butschster requested changes

2022-12-16 07:19 UTC, butschster commented on composer.json
> +    "cycle/schema-renderer": "^1.3",
```suggestion
    "cycle/schema-renderer": "^1.2",
```

2023-01-03 14:09 UTC, butschster approved these changes

2023-01-03 14:09 UTC, merged